spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: app
    virtual-host: /

# implementation 'org.springframework.boot:spring-boot-starter-amqp'
# implementation 'org.springframework.boot:spring-boot-starter-jackson'
